INIT_ML = 0
INIT_RAND = 1

UPDATEHYPER_ON = 0
UPDATEHYPER_OFF = 1

PREDVAR_DOES_NOT_COMPUTE = 0
PREDVAR_COMPUTE_AND_OUTPUT = 1
PREDVAR_FAST_COMPUTATION = 2

VERBOSE_NO_ANY = 0
VERBOSE_TEXT = 1
VERBOSE_IMAGE_PLOT = 2
VERBOSE_HINTON_PLOT = 3